### ISSUE TITLE
ArcGIS Workspace target - Add configuration validator to check that ArcGIS MDG Technology is enabled in EA

### ISSUE THREAD

**Issue by jechterhoff** [ShapeChange/ShapeChange#123]
The ArcGIS Workspace target adds new elements to an EA repository using qualified names from the UML Profile of the ArcGIS MDG Technology, for example "ArcGIS::ObjectClass". If the ArcGIS MDG is not enabled in the EA environment in which ShapeChange is executed, adding such an element will result in an exception like the following:

```
java.lang.Exception: Invalid type
        at org.sparx.Collection.comAddNew(Native Method)
        at org.sparx.Collection.AddNew(Collection.java:122)
        ...
```

ShapeChange validates the configuration before processing the input model. This validation phase can perform a number of checks. The validation is intended to catch common configuration mistakes before a potentially quite time consuming run of ShapeChange is performed, only to fail towards the end due to a configuration issue.

The EA API supports checking if an MDG Technology with a specific ID is enabled for a given repository. An ArcGIS Workspace configuration validator should be added to perform such a check.

**Comment by jechterhoff** [comment]
The check is automatically performed at the start of processing, more specifically while the configuration is validated.
