### ISSUE TITLE
SqlDdl target - Casting error in statement sort

### ISSUE THREAD

**Issue by jhevenor** [ShapeChange/ShapeChange#296]
Good morning, 
I'm brand new to ShapeChange and EA and don't really know what I'm doing.  I have some documentation from a partner that I'm working through to create a profile of a data model.  I've had a clean run with a very sparse profile, but as I try to expand that I start to get the following error: 

```cmd
PF-E class de.interactive_instruments.ShapeChange.Target.SQL.structure.CreateIndex cannot be cast to class de.interactive_instruments.ShapeChange.Target.SQL.structure.CreateTable (de.interactive_instruments.ShapeChange.Target.SQL.structure.CreateIndex and de.interactive_instruments.ShapeChange.Target.SQL.structure.CreateTable are in unnamed module of loader 'app')
java.lang.ClassCastException: class de.interactive_instruments.ShapeChange.Target.SQL.structure.CreateIndex cannot be cast to class de.interactive_instruments.ShapeChange.Target.SQL.structure.CreateTable (de.interactive_instruments.ShapeChange.Target.SQL.structure.CreateIndex and de.interactive_instruments.ShapeChange.Target.SQL.structure.CreateTable are in unnamed module of loader 'app')
        at de.interactive_instruments.ShapeChange.Target.SQL.StatementSortAlphabetic.compare(StatementSortAlphabetic.java:208)
        at de.interactive_instruments.ShapeChange.Target.SQL.StatementSortAlphabetic.compare(StatementSortAlphabetic.java:59)
        at java.base/java.util.TimSort.binarySort(Unknown Source)
        at java.base/java.util.TimSort.sort(Unknown Source)
        at java.base/java.util.Arrays.sort(Unknown Source)
        at java.base/java.util.ArrayList.sort(Unknown Source)
        at java.base/java.util.Collections.sort(Unknown Source)
        at de.interactive_instruments.ShapeChange.Target.SQL.SqlBuilder.process(SqlBuilder.java:2591)
        at de.interactive_instruments.ShapeChange.Target.SQL.SqlDdl.writeAll(SqlDdl.java:865)
        at de.interactive_instruments.ShapeChange.Converter.executeTargets(Converter.java:782)
        at de.interactive_instruments.ShapeChange.Converter.executeTransformations(Converter.java:624)
        at de.interactive_instruments.ShapeChange.Converter.executeTransformations(Converter.java:627)
        at de.interactive_instruments.ShapeChange.Converter.convert(Converter.java:310)
        at de.interactive_instruments.ShapeChange.Converter.convert(Converter.java:157)
        at de.interactive_instruments.ShapeChange.Main.main(Main.java:110)
```
When I dig into the code I see that that relates to this statement:

```java
// StatementSortAlphabetic.java
String tableName_o1;
String tableName_o2;
if (SqlConstants.STATEMENT_SORT_USES_SCHEMA_NAME) {
    tableName_o1 = ((CreateTable) o1).getTable().getFullName();  // error here, line 208
    tableName_o2 = ((CreateTable) o2).getTable().getFullName();
} else {
    tableName_o1 = ((CreateTable) o1).getTable().getName();
    tableName_o2 = ((CreateTable) o2).getTable().getName();
}
return tableName_o1.compareTo(tableName_o2);
```
A CreateIndex object is getting passed here according to the error.  I've tried this with the postgres and sqlserver output targets and I get the same result.  Using ShapeChange v2.12  but confirmed the same error in v2.11

My EA project is large and I'm not sure how to pare it down to a suitable test case. I'll work on finding something suitable and follow up. It's very possible that my config is wrong, please advise.  My attempts at googling the error have found nothing. Any guidance is appreciated.

**Comment by jechterhoff** [comment]
Hello @jhevenor,
Thanks for reporting this. Yes, there is a bug since casting of o1 and o2 to CreateTable at that point does not make sense.
Can you update your source code and try again with the following (replacing lines 207 to 213 in StatementSortAlphabetic.java):

```java
		if (SqlConstants.STATEMENT_SORT_USES_SCHEMA_NAME) {
		    tableName_o1 = ci1.getTable().getFullName();
		    tableName_o2 = ci2.getTable().getFullName();
		} else {
		    tableName_o1 = ci1.getTable().getName();
		    tableName_o2 = ci2.getTable().getName();
		}
```
Does that work for you?

**Comment by jhevenor** [comment]
Thank you @jechterhoff !  It took me a couple days to get a chance to get a dev environment running.  Sorry for the delay getting back here.     This has fixed the crash I was getting.

**Comment by jechterhoff** [comment]
Perfect. Thanks for setting up a dev environment. I was not sure if you had to do so, or if you already had one (since you were able to point out the code fragment where the error occurred). When I was about to create a new ShapeChange snapshot with my code change, so that you could use that in order to test the change with your project, a separate issue came up which I had to investigate first. Thus the delay on my part.
