### ISSUE TITLE
Ontology target - Error when generating codelists

### ISSUE THREAD

**Issue by DiegoVinasco** [ShapeChange/ShapeChange#431]
Hello,

I've run into the following null pointer exception when trying to generate code lists from the CityGML 3.0 UML model using ShapeChange 3.1.0 and java openjdk version 11.0.21. I'd like to be able to transform these code lists using either the `"rule-owl-cls-codelist-19150-2"` OWL ontology target encoding rule. Any help with this would be appreciated.

```
PF-I ---------- Semantic validation of ShapeChange configuration: START ----------
PF-I --- Validating transformer with @id 'ACMAPPER' ...
PF-I --- Validating target with @class 'de.interactive_instruments.ShapeChange.Target.Ontology.OWLISO19150' and @inputs 'ACMAPPER' ...
PF-I ---------- Semantic validation of ShapeChange configuration: COMPLETE ----------
W Could not establish a category for element 'Color', having well-known stereotype <<basictype>> and encoding rule 'iso19136_2007'; setting category to 'unknown'.
W Could not establish a category for element 'ColorPlusOpacity', having well-known stereotype <<basictype>> and encoding rule 'iso19136_2007'; setting category to 'unknown'.
W Could not establish a category for element 'TransformationMatrix2x2', having well-known stereotype <<basictype>> and encoding rule 'iso19136_2007'; setting category to 'unknown'.        
W Could not establish a category for element 'DoubleBetween0and1', having well-known stereotype <<basictype>> and encoding rule 'iso19136_2007'; setting category to 'unknown'.
W Could not establish a category for element 'DoubleBetween0and1List', having well-known stereotype <<basictype>> and encoding rule 'iso19136_2007'; setting category to 'unknown'.
W Could not establish a category for element 'TransformationMatrix4x4', having well-known stereotype <<basictype>> and encoding rule 'iso19136_2007'; setting category to 'unknown'.        
W Could not establish a category for element 'MeasureOrNilReasonList', having well-known stereotype <<basictype>> and encoding rule 'notencoded'; setting category to 'unknown'.
W Could not establish a category for element 'DoubleOrNilReasonList', having well-known stereotype <<basictype>> and encoding rule 'notencoded'; setting category to 'unknown'.
W Could not establish a category for element 'ID', having well-known stereotype <<basictype>> and encoding rule 'notencoded'; setting category to 'unknown'.
W Could not establish a category for element 'Code', having well-known stereotype <<basictype>> and encoding rule 'notencoded'; setting category to 'unknown'.
W Could not establish a category for element 'DoubleList', having well-known stereotype <<basictype>> and encoding rule 'notencoded'; setting category to 'unknown'.
W Could not establish a category for element 'IntegerBetween0and3', having well-known stereotype <<basictype>> and encoding rule 'iso19136_2007'; setting category to 'unknown'.
W Could not establish a category for element 'TransformationMatrix3x4', having well-known stereotype <<basictype>> and encoding rule 'iso19136_2007'; setting category to 'unknown'.        
W Restriction of property 'boundary' in class 'HollowSpace' from supertype 'AbstractSpace'.
W Restriction of property 'boundary' in class 'WaterBody' from supertype 'AbstractSpace'.
W Restriction of property 'boundary' in class 'BridgeRoom' from supertype 'AbstractSpace'.
W Restriction of property 'boundary' in class 'BuildingRoom' from supertype 'AbstractSpace'.
W Restriction of property 'boundary' in class 'Storey' from supertype 'AbstractSpace'.
W Restriction of property 'boundary' in class 'AbstractConstruction' from supertype 'AbstractSpace'.
W Restriction of property 'boundary' in class 'Door' from supertype 'AbstractSpace'.
W Restriction of property 'boundary' in class 'AbstractConstructiveElement' from supertype 'AbstractSpace'.
W Restriction of property 'boundary' in class 'AbstractInstallation' from supertype 'AbstractSpace'.
W Restriction of property 'boundary' in class 'Window' from supertype 'AbstractSpace'.
W Restriction of property 'boundary' in class 'TrafficSpace' from supertype 'AbstractSpace'.
W Restriction of property 'boundary' in class 'AuxiliaryTrafficSpace' from supertype 'AbstractSpace'.
PF-I Now processing transformation 'ACMAPPER' for input ID: 'INPUT'.
PF-I ---------- TransformationManager postprocessing: validating constraints ----------
PF-I Performed transformation for transformer ID 'ACMAPPER' for input ID: 'INPUT'.
-------------------------------------------------
PF-I Application schema found, package name: 'CityObjectGroup', target namespace: 'http://www.opengis.net/citygml/cityobjectgroup/3.0'
PF-I Now processing target 'ISO 19150-2 OWL Ontology' for input 'ACMAPPER'.
PF-I Application schema found, package name: 'Core', target namespace: 'http://www.opengis.net/citygml/3.0'
PF-I Now processing target 'ISO 19150-2 OWL Ontology' for input 'ACMAPPER'.
PF-I Application schema found, package name: 'LandUse', target namespace: 'http://www.opengis.net/citygml/landuse/3.0'
PF-I Now processing target 'ISO 19150-2 OWL Ontology' for input 'ACMAPPER'.
PF-I Application schema found, package name: 'Relief', target namespace: 'http://www.opengis.net/citygml/relief/3.0'
PF-I Now processing target 'ISO 19150-2 OWL Ontology' for input 'ACMAPPER'.
PF-I Application schema found, package name: 'Tunnel', target namespace: 'http://www.opengis.net/citygml/tunnel/3.0'
PF-I Now processing target 'ISO 19150-2 OWL Ontology' for input 'ACMAPPER'.
PF-I Application schema found, package name: 'Vegetation', target namespace: 'http://www.opengis.net/citygml/vegetation/3.0'
PF-I Now processing target 'ISO 19150-2 OWL Ontology' for input 'ACMAPPER'.
PF-I Application schema found, package name: 'WaterBody', target namespace: 'http://www.opengis.net/citygml/waterbody/3.0'
PF-I Now processing target 'ISO 19150-2 OWL Ontology' for input 'ACMAPPER'.
PF-I Application schema found, package name: 'Appearance', target namespace: 'http://www.opengis.net/citygml/appearance/3.0'
PF-I Now processing target 'ISO 19150-2 OWL Ontology' for input 'ACMAPPER'.
PF-I Application schema found, package name: 'Bridge', target namespace: 'http://www.opengis.net/citygml/bridge/3.0'
PF-I Now processing target 'ISO 19150-2 OWL Ontology' for input 'ACMAPPER'.
PF-I Application schema found, package name: 'Building', target namespace: 'http://www.opengis.net/citygml/building/3.0'
PF-I Now processing target 'ISO 19150-2 OWL Ontology' for input 'ACMAPPER'.
PF-I Application schema found, package name: 'Construction', target namespace: 'http://www.opengis.net/citygml/construction/3.0'
PF-I Now processing target 'ISO 19150-2 OWL Ontology' for input 'ACMAPPER'.
PF-I Application schema found, package name: 'Versioning', target namespace: 'http://www.opengis.net/citygml/versioning/3.0'
PF-I Now processing target 'ISO 19150-2 OWL Ontology' for input 'ACMAPPER'.
PF-I Application schema found, package name: 'Dynamizer', target namespace: 'http://www.opengis.net/citygml/dynamizer/3.0'
PF-I Now processing target 'ISO 19150-2 OWL Ontology' for input 'ACMAPPER'.
PF-I Application schema found, package name: 'PointCloud', target namespace: 'http://www.opengis.net/citygml/pointcloud/3.0'
PF-I Now processing target 'ISO 19150-2 OWL Ontology' for input 'ACMAPPER'.
PF-I Application schema found, package name: 'Generics', target namespace: 'http://www.opengis.net/citygml/generics/3.0'
PF-I Now processing target 'ISO 19150-2 OWL Ontology' for input 'ACMAPPER'.
PF-I Application schema found, package name: 'Transportation', target namespace: 'http://www.opengis.net/citygml/transportation/3.0'
PF-I Now processing target 'ISO 19150-2 OWL Ontology' for input 'ACMAPPER'.
PF-I Application schema found, package name: 'Workspace', target namespace: 'https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/Workspace/3.0/workspace'
PF-I Now processing target 'ISO 19150-2 OWL Ontology' for input 'ACMAPPER'.
PF-I Application schema found, package name: 'Document', target namespace: 'https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/Document/3.0/document'
PF-I Now processing target 'ISO 19150-2 OWL Ontology' for input 'ACMAPPER'.
PF-I Application schema found, package name: 'CityFurniture', target namespace: 'http://www.opengis.net/citygml/cityfurniture/3.0'
PF-I Now processing target 'ISO 19150-2 OWL Ontology' for input 'ACMAPPER'.
PF-E java.lang.NullPointerException encountered. Processing was interrupted unexpectedly.
P ... <no exception message available>
java.lang.NullPointerException
        at de.interactive_instruments.ShapeChange.Target.Ontology.OntologyModel.addCodelist(OntologyModel.java:3013)
        at de.interactive_instruments.ShapeChange.Target.Ontology.OntologyModel.createClasses(OntologyModel.java:589)
        at de.interactive_instruments.ShapeChange.Target.Ontology.OWLISO19150.writeAll(OWLISO19150.java:1011)
        at de.interactive_instruments.ShapeChange.Converter.executeTargets(Converter.java:831)
        at de.interactive_instruments.ShapeChange.Converter.executeTransformations(Converter.java:645)
        at de.interactive_instruments.ShapeChange.Converter.convert(Converter.java:321)
        at de.interactive_instruments.ShapeChange.Converter.convert(Converter.java:159)
        at de.interactive_instruments.ShapeChange.Main.main(Main.java:110)
```

My configuration file is structured as followed:

```xml
<ShapeChangeConfiguration xmlns:xi="http://www.w3.org/2001/XInclude" xmlns="http://www.interactive-instruments.de/ShapeChange/Configuration/1.1" xmlns:sc="http://www.interactive-instruments.de/ShapeChange/Configuration/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.interactive-instruments.de/ShapeChange/Configuration/1.1 http://shapechange.net/resources/schema/ShapeChangeConfiguration.xsd">
  <input>
    <!-- <parameter name="inputModelType" value="EA7"/> -->
    <parameter name="inputModelType" value="SCXML"/>
    <parameter name="inputFile" value='$input$'/>
    <parameter name="appSchemaNamespaceRegex" value="^(https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/|http://www.opengis.net/citygml/).*"/>
    <parameter name="checkingConstraints" value="disabled"/>
    <parameter name="addTaggedValues" value="itemType"/>
    <xi:include href="http://shapechange.net/resources/config/StandardAliases.xml"/>
    <stereotypeAliases>
      <StereotypeAlias wellknown="BasicType" alias="basictype"/>
      <StereotypeAlias wellknown="property" alias="Property"/>
      <StereotypeAlias wellknown="version" alias="Version"/>
      <StereotypeAlias wellknown="FeatureType" alias="TopLevelFeatureType"/>
    </stereotypeAliases>
  </input>
  <log>
    <parameter name="reportLevel" value="WARNING" />
    <parameter name="logFile" value="logs/log.xml" />
  </log>
  <!-- Proposed by OGC document number 16-020  http://docs.opengeospatial.org/per/16-020.html#rdf_cr_associationclass -->
  <transformers>
    <Transformer id="ACMAPPER" class="de.interactive_instruments.ShapeChange.Transformation.Flattening.AssociationClassMapper" mode="enabled"/>
    <!-- Union alternative 1 transformer -->
    <Transformer id="FLATTENER1" class="de.interactive_instruments.ShapeChange.Transformation.Flattening.Flattener" input="ACMAPPER" mode="disabled">
      <parameters>
        <ProcessParameter name="includeUnionIdentifierTaggedValue" value="true"/>
        <ProcessParameter name="separatorForPropertyFromUnion" value="."/>
        <ProcessParameter name="flattenObjectTypes" value="false"/>
        <ProcessParameter name="flattenDataTypesExcludeRegex" value=".*"/>
        <ProcessParameter name="setMinCardinalityToZeroWhenMergingUnion" value="false"/>
      </parameters>
      <rules>
        <ProcessRuleSet name="flattener">
          <rule name="rule-trf-prop-flatten-types"/>
        </ProcessRuleSet>
      </rules>
    </Transformer>
    <Transformer class="de.interactive_instruments.ShapeChange.Transformation.Flattening.Flattener" input="ACMAPPER" id="FLATTENER2" mode="disabled">
      <parameters>
        <ProcessParameter name="includeUnionIdentifierTaggedValue" value="true"/>
      </parameters>
      <rules>
        <ProcessRuleSet name="flattener">
          <rule name="rule-trf-cls-replace-with-union-properties"/>
        </ProcessRuleSet>
      </rules>
    </Transformer>
  </transformers>
  <targets>
    <!-- <TargetOwl class="de.interactive_instruments.ShapeChange.Target.Ontology.OWLISO19150" mode="enabled"> -->
    <TargetOwl class="de.interactive_instruments.ShapeChange.Target.Ontology.OWLISO19150" mode="enabled" inputs="ACMAPPER">
      <targetParameter name="outputDirectory" value="$output$"/>
      <!-- <targetParameter name="outputDirectory" value="../Data-IO/OWL/CityGML_3.0_Conceptual_Model"/> -->
      <targetParameter name="defaultEncodingRule" value="CityGML_RDF_Encoding_Rules"/>
      <targetParameter name="defaultTypeImplementation" value="owl:Thing"/>
      <targetParameter name="URIbase" value="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0"/>
      <targetParameter name="language" value="en"/>
      <xi:include href="https://shapechange.net/resources/config/StandardNamespaces-owl.xml"/>
      <namespaces>
        <!-- CityGML 3.0 namespaces -->
        <Namespace nsabr="app" ns="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/appearance#"/>
        <Namespace nsabr="brid" ns="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/bridge#"/>
        <Namespace nsabr="bldg" ns="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/building#"/>
        <Namespace nsabr="pcl" ns="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/pointcloud#"/>
        <Namespace nsabr="frn" ns="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/cityfurniture#"/>
        <Namespace nsabr="grp" ns="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/cityobjectgroup#"/>
        <Namespace nsabr="con" ns="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/construction#"/>
        <Namespace nsabr="core" ns="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/core#"/>
        <Namespace nsabr="dyn" ns="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/dynamizer#"/>
        <Namespace nsabr="gen" ns="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/generics#"/>
        <Namespace nsabr="luse" ns="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/landuse#"/>
        <Namespace nsabr="dem" ns="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/relief#"/>
        <Namespace nsabr="tran" ns="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/transportation#"/>
        <Namespace nsabr="tun" ns="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/tunnel#"/>
        <Namespace nsabr="veg" ns="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/vegetation#"/>
        <Namespace nsabr="vers" ns="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/versioning#"/>
        <Namespace nsabr="wtr" ns="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/waterbody#"/>
        <Namespace nsabr="xAL" ns="urn:oasis:names:tc:ciq:xal:3"/>
        <!-- ADE namespaces -->
        <Namespace nsabr="doc" ns="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/Document/3.0/document#"/>
        <Namespace nsabr="wksp" ns="https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/Workspace/3.0/workspace#"/>
        <!-- ISO TC211 namespaces -->
        <Namespace nsabr="iso19103" ns="http://def.isotc211.org/iso19103/2005/UnitsOfMeasure#"/>
        <Namespace nsabr="iso19107-cm" ns="http://def.isotc211.org/iso19107/2003/CoordinateGeometry#"/>
        <Namespace nsabr="iso19107-gc" ns="http://def.isotc211.org/iso19107/2003/GeometricComplex#"/>
        <Namespace nsabr="iso19109" ns="http://def.isotc211.org/iso19109/2015/GeneralFeatureModel#"/>
        <Namespace nsabr="iso19111-2007" ns="http://def.isotc211.org/iso19111/2007/CoordinateReferenceSystems#"/>
        <Namespace nsabr="iso19111-2019" ns="http://def.isotc211.org/iso19111/2019/CoordinateReferenceSystems#"/>
        <Namespace nsabr="iso19123" ns="http://def.isotc211.org/iso19123/2005/DiscreteCoverages#"/>
        <Namespace nsabr="iso19136-bt" ns="http://def.isotc211.org/iso19136/2007/BasicTypes#"/>
        <Namespace nsabr="orph" ns="http://def.isotc211.org/orphans/Orphans#"/>
        <!-- OGC Standard namespaces -->
        <Namespace nsabr="tsml" ns="http://www.opengis.net/tsml/1.0#"/>
        <Namespace nsabr="sos" ns="http://www.opengis.net/sos/1.0#"/>
      </namespaces>
      <descriptorTargets>
        <!-- <DescriptorTarget target="skos:prefLabel" template="[[name]]"/> -->
        <DescriptorTarget target="rdfs:label" template="[[name]]"/>
        <DescriptorTarget target="skos:definition" template="[[definition]]"/>
        <DescriptorTarget target="rdfs:comment" template="[[description]]"/>
      </descriptorTargets>
      <xi:include href="https://shapechange.net/resources/config/StandardMapEntries_iso19103-owl.xml"/>
      <xi:include href="https://shapechange.net/resources/config/StandardMapEntries_iso19107-owl-gml.xml"/>
      <xi:include href="https://shapechange.net/resources/config/StandardMapEntries_iso19108-owl.xml"/>
      <xi:include href="https://shapechange.net/resources/config/StandardMapEntries_iso19136_2007-owl.xml"/>
      <xi:include href="StandardMapEntries_iso19107-owl.xml"/>
      <rdfMapEntries>
        <RdfTypeMapEntry type="AnyFeature" target="iso19109:AnyFeature"/>
        <RdfTypeMapEntry type="CV_DiscreteGridPointCoverage" target="iso19123:CV_DiscreteGridPointCoverage"/>
        <RdfTypeMapEntry type="EngineeringCRS" target="iso19111-2019:EngineeringCRS"/>
        <RdfTypeMapEntry type="MeasureOrNilReasonList" target="iso19136-bt:MeasureOrNilReasonList"/>
        <RdfTypeMapEntry type="SC_CRS" target="iso19111-2007:SC_CRS"/>
        <RdfTypeMapEntry type="UnitOfMeasure" target="sc:Measure"/>
        <RdfTypeMapEntry type="TM_Duration" target="time:TemporalDuration"/>
        <RdfTypeMapEntry type="TM_Period" target="time:Interval"/>
        <RdfTypeMapEntry type="GM_TriangulatedSurface" target="iso19107-cm:GM_TriangulatedSurface"/>
        <RdfTypeMapEntry type="Sequence&lt;Real&gt;" target="orph:Sequence.lt.Real.gt."/>
        <RdfTypeMapEntry type="Code" target="iso19136-bt:Code"/>
        <RdfTypeMapEntry type="Sequence&lt;DoubleBetween0and1&gt;" target="orph:Sequence.lt.MeasureOrNilReason.gt."/>
        <RdfTypeMapEntry type="doubleList" target="iso19136-bt:doubleList"/>
        <RdfTypeMapEntry type="GetObservationResponse" target="sos:GetObservationResponse"/>
      </rdfMapEntries>
      <rules>
        <EncodingRule name="CityGML_RDF_Encoding_Rules">
          <rule name="rule-owl-pkg-ontologyName-iso191502"/>
          <!-- <rule name="rule-owl-pkg-ontologyName-code"/> -->
          <!-- <rule name="rule-owl-pkg-singleOntologyPerSchema"/> -->
          <rule name="rule-owl-pkg-importISO191502Base"/>
          <rule name="rule-owl-cls-iso191502IsAbstract"/>
          <!-- <rule name="rule-owl-cls-enumerationAsCodelist"/> -->
          <rule name="rule-owl-cls-iso191502Enumeration"/>
          <rule name="rule-owl-cls-encode-featuretypes"/>
          <rule name="rule-owl-cls-encode-objecttypes"/>
          <rule name="rule-owl-cls-encode-mixintypes"/>
          <rule name="rule-owl-cls-encode-datatypes"/>
          <rule name="rule-owl-cls-encode-basictypes"/>
          <!-- <rule name="rule-owl-cls-codelist-external"/> -->
          <rule name="rule-owl-cls-codelist-19150-2"/>
          <!-- <rule name="rule-owl-cls-codelist-19150-2-skos-collection"/> -->
          <rule name="rule-owl-cls-generalization"/>
          <rule name="rule-owl-cls-disjoint-classes"/>
          <!-- <rule name="rule-owl-cls-union"/> -->
          <rule name="rule-owl-prop-general"/>
          <rule name="rule-owl-prop-iso191502-naming"/>
          <rule name="rule-owl-prop-localScopeAll"/>
          <!-- <rule name="rule-owl-prop-globalScopeAttributes"/> -->
          <!-- <rule name="rule-owl-prop-globalScopeByUniquePropertyName"/> -->
          <!-- <rule name="rule-owl-prop-globalScopeByConversionParameter"/> -->
          <rule name="rule-owl-prop-multiplicityAsQualifiedCardinalityRestriction"/>
          <!-- <rule name="rule-owl-prop-multiplicityAsUnqualifiedCardinalityRestriction"/> -->
          <rule name="rule-owl-prop-voidable-as-minCardinality0"/>
          <rule name="rule-owl-prop-range-global"/>
          <rule name="rule-owl-prop-range-local-withUniversalQuantification"/>
          <rule name="rule-owl-prop-inverseOf"/>
          <rule name="rule-owl-prop-mapping-compare-specifications"/>
          <!-- <rule name="rule-owl-all-constraints-humanReadableTextOnly"/> -->
          <rule name="rule-owl-all-constraints-byConstraintMapping"/>
        </EncodingRule>
      </rules>
    </TargetOwl>
  </targets>
</ShapeChangeConfiguration>
```

The input UML model can be found [here](https://github.com/VCityTeam/UD-Graph/blob/master/Transformations/test-data/UML/CityGML_3.0-workspaces-documents_shapechange-export.xml). Its an extension of the original [CityGML 3.0 UML model](https://www.ogc.org/standard/citygml/) exported from EA and transformed to a SCXML model.

In case there is an issue with how the code lists were created here is a code list `RelationTypeValue` that is structured as follows in the SCXML model:
```xml
                <sc:Class>
                  <sc:name>RelationTypeValue</sc:name>
                  <sc:id>7890</sc:id>
                  <sc:stereotypes>
                    <sc:Stereotype>codelist</sc:Stereotype>
                  </sc:stereotypes>
                  <sc:descriptors>
                    <sc:definition>
                      <sc:descriptorValues>
                        <sc:DescriptorValue>RelationTypeValue is a code list used to classify city object relations.</sc:DescriptorValue>
                      </sc:descriptorValues>
                    </sc:definition>
                    <sc:documentation>
                      <sc:descriptorValues>
                        <sc:DescriptorValue>RelationTypeValue is a code list used to classify city object relations.</sc:DescriptorValue>
                      </sc:descriptorValues>
                    </sc:documentation>
                  </sc:descriptors>
                  <sc:taggedValues>
                    <sc:TaggedValue>
                      <sc:name>asDictionary</sc:name>
                      <sc:values>
                        <sc:Value>True</sc:Value>
                      </sc:values>
                    </sc:TaggedValue>
                    <sc:TaggedValue>
                      <sc:name>xsdEncodingRule</sc:name>
                    </sc:TaggedValue>
                  </sc:taggedValues>
                  <sc:subtypes>
                    <sc:SubtypeId>7891</sc:SubtypeId>
                    <sc:SubtypeId>7892</sc:SubtypeId>
                    <sc:SubtypeId>7893</sc:SubtypeId>
                  </sc:subtypes>
                </sc:Class>
                <sc:Class>
                  <sc:name>TopologicalRelationTypeValue</sc:name>
                  <sc:id>7891</sc:id>
                  <sc:stereotypes>
                    <sc:Stereotype>codelist</sc:Stereotype>
                  </sc:stereotypes>
                  <sc:descriptors>
                    <sc:definition>
                      <sc:descriptorValues>
                        <sc:DescriptorValue>TopologicalRelationTypeValue is a code list used to classify topological city object relations.</sc:DescriptorValue>
                      </sc:descriptorValues>
                    </sc:definition>
                    <sc:documentation>
                      <sc:descriptorValues>
                        <sc:DescriptorValue>TopologicalRelationTypeValue is a code list used to classify topological city object relations.</sc:DescriptorValue>
                      </sc:descriptorValues>
                    </sc:documentation>
                  </sc:descriptors>
                  <sc:taggedValues>
                    <sc:TaggedValue>
                      <sc:name>asDictionary</sc:name>
                      <sc:values>
                        <sc:Value>True</sc:Value>
                      </sc:values>
                    </sc:TaggedValue>
                    <sc:TaggedValue>
                      <sc:name>xsdEncodingRule</sc:name>
                    </sc:TaggedValue>
                  </sc:taggedValues>
                  <sc:supertypes>
                    <sc:SupertypeId>7890</sc:SupertypeId>
                  </sc:supertypes>
                </sc:Class>
                <sc:Class>
                  <sc:name>OtherRelationTypeValue</sc:name>
                  <sc:id>7892</sc:id>
                  <sc:stereotypes>
                    <sc:Stereotype>codelist</sc:Stereotype>
                  </sc:stereotypes>
                  <sc:descriptors>
                    <sc:definition>
                      <sc:descriptorValues>
                        <sc:DescriptorValue>OtherRelationTypeValue is a code list used to classify other types of city object relations.</sc:DescriptorValue>
                      </sc:descriptorValues>
                    </sc:definition>
                    <sc:documentation>
                      <sc:descriptorValues>
                        <sc:DescriptorValue>OtherRelationTypeValue is a code list used to classify other types of city object relations.</sc:DescriptorValue>
                      </sc:descriptorValues>
                    </sc:documentation>
                  </sc:descriptors>
                  <sc:taggedValues>
                    <sc:TaggedValue>
                      <sc:name>asDictionary</sc:name>
                      <sc:values>
                        <sc:Value>True</sc:Value>
                      </sc:values>
                    </sc:TaggedValue>
                    <sc:TaggedValue>
                      <sc:name>xsdEncodingRule</sc:name>
                    </sc:TaggedValue>
                  </sc:taggedValues>
                  <sc:supertypes>
                    <sc:SupertypeId>7890</sc:SupertypeId>
                  </sc:supertypes>
                </sc:Class>
                <sc:Class>
                  <sc:name>TemporalRelationTypeValue</sc:name>
                  <sc:id>7893</sc:id>
                  <sc:stereotypes>
                    <sc:Stereotype>codelist</sc:Stereotype>
                  </sc:stereotypes>
                  <sc:descriptors>
                    <sc:definition>
                      <sc:descriptorValues>
                        <sc:DescriptorValue>TemporalRelationTypeValue is a code list used to classify temporal city object relations.</sc:DescriptorValue>
                      </sc:descriptorValues>
                    </sc:definition>
                    <sc:documentation>
                      <sc:descriptorValues>
                        <sc:DescriptorValue>TemporalRelationTypeValue is a code list used to classify temporal city object relations.</sc:DescriptorValue>
                      </sc:descriptorValues>
                    </sc:documentation>
                  </sc:descriptors>
                  <sc:taggedValues>
                    <sc:TaggedValue>
                      <sc:name>asDictionary</sc:name>
                      <sc:values>
                        <sc:Value>True</sc:Value>
                      </sc:values>
                    </sc:TaggedValue>
                    <sc:TaggedValue>
                      <sc:name>xsdEncodingRule</sc:name>
                    </sc:TaggedValue>
                  </sc:taggedValues>
                  <sc:supertypes>
                    <sc:SupertypeId>7890</sc:SupertypeId>
                  </sc:supertypes>
                </sc:Class>
```

**Comment by jechterhoff** [comment]
Hi @DiegoVinasco,

I suggest you activate `rule-owl-pkg-singleOntologyPerSchema` - then the ontology for the code individuals is generated and found. Or do you have a particular reason for not using that conversion rule?

**Comment by jechterhoff** [comment]
... adding to what I wrote earlier: using `rule-owl-pkg-singleOntologyPerSchema` in your encoding rule will avoid the NPE. I just pushed a fix for the default encoding behavior, i.e. for cases in which that conversion rule is not used.

**Comment by DiegoVinasco** [comment]
Hi @jechterhoff, that worked!

Since we only have 1 schema with multiple packages in CityGML 3.0, I didn't think this rule was necessary.

However, the ontologies are now generating as expected. Thank you for your quick reply!

**Comment by jechterhoff** [comment]
Actually, CityGML 3.0 consists of multiple application schemas: 

* «ApplicationSchema» Appearance
* «ApplicationSchema» Bridge
* ...

But, in any case, the issue you reported was a bug (which will be fixed in the next version), and adding `rule-owl-pkg-singleOntologyPerSchema` to the encoding rule is the workaround for the current version.
